Add --exclude-string & daily ES indexes (#50)
* Add: --exclude-string

* Add: rotating ES index

* Fix: first logging setup when ES is used was missing

* refactor: refactor logging and simplify GetOutboundIP in network module

- Remove unused import of &#34;log&#34;
- Replace log.Fatal with logrus.Errorf and add retry logic for network error
- Simplify return statement for GetOutboundIP using method chaining

Signed-off-by: Corentin Barreau <corentin@archive.org>

* Fix: panic from improper redefinition of net.Conn

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbd8d78]

goroutine 99 [running]:
github.com/CorentinB/Zeno/internal/pkg/utils.GetOutboundIP()
        /tmp/Zeno/internal/pkg/utils/ip.go:24 +0xf8

* feat: rework genLogFields to ensure we are operating more efficiently.

Using a syncmap we are storing values for IP and Version to avoid potentially expensive calls to both, as they are very unlikely to change in the middle of a job.

* Fetch IP address every 10 seconds

* refactor: refactor `GetOutboundIP` function variable declaration syntax

- Refactor `GetOutboundIP` function to use shorter variable declaration syntax.

Signed-off-by: Corentin Barreau <corentin@archive.org>

* refactor: refactor time calculation to use UTC

- Change time calculation to use UTC instead of local time

Signed-off-by: Corentin Barreau <corentin@archive.org>

---------

Signed-off-by: Corentin Barreau <corentin@archive.org>
Co-authored-by: Jake LaFountain <jakelf@archive.org>